# https://taskfile.dev

version: '3'

tasks:
  l01:
    cmds:
      - quarto preview lessons/L01.qmd --output-dir output
  l02:
    cmds:
      - quarto preview lessons/L02.qmd --output-dir output
  l03:
    cmds:
      - quarto preview lessons/L03.qmd --output-dir output
  l04:
    cmds:
      - quarto preview lessons/L04.qmd --output-dir output
  l05:
    cmds:
      - quarto preview lessons/L05.qmd --output-dir output
  l10:
    cmds:
      - quarto preview lessons/L10.qmd --output-dir output
  l11:
    cmds:
      - quarto preview lessons/L11.qmd --output-dir output
